### ISSUE TITLE
[CHORES] Sequelize Basic Structure and Models

### ISSUE THREAD

**Issue by ifeLight** [BuildForSDG/Team-006-Backend#10]
**Database Status**
As of now we have **_graphically_** designed a database structure that will help us show the way our database is need to be designed on the backend, and we will be using **_Sequelize_** as the **ORM**.
 > [The Link to the pictorial design](https://dbdiagram.io/d/5eb422a239d18f5553fed87c)
 
**TODO**
1. Add the various sequelize npm modules such as [Sequelize](https://www.npmjs.com/package/sequelize) && [Sequelize-cli](https://www.npmjs.com/package/sequelize-cli)

2. Also the creation of  Sequelize models/index.js file

3. The creation of the Models file for each database and configure their relationships

4. If there will be need for a migration file, to kickstart the databse when launched, it can be included.

> This article explains it all [Getting Started with Node, Express and Postgres Using Sequelize](https://scotch.io/tutorials/getting-started-with-node-express-and-postgres-using-sequelize)

>> For Further research we can visit the [Sequelize official website for more.](https://sequelize.org/)

**Acceptance Criteria**
Fully embedded the pictorial design into the app without touching the database with our raw hands

**Comment by dallintine** [comment]
please can i view the design am not seeing it

**Comment by ifeLight** [comment]
@dallintine have updated it
