### ISSUE TITLE
[chore]: Setup CI/CD automation and 3rd Party Services

### ISSUE THREAD

**Issue by dave-ok** [BuildForSDG/Team-006-Backend#11]
**Description**

Setup continuous and automated testing and deployment of the backend server using Travis CI, and heroku. The credentials for various services need to be obtained and maintained in a central location for ease of access to team members.

**Aceptance Criteria**
- Create Google account for this project
- Create google doc for storing credentials
- Create app and setup teams on heroku
- Create postgres DB on heroku
- Setup Travis CI for test and deployment
- Setup coveralls for test coverage
- Create firebase project and web app
- Create facebook app for this project
- Create cloudinary account for this project
- Setup google maps API integration * (requires billing info)

**Comment by dallintine** [comment]
@dave-ok  how are we going to archive all this explain in detail

**Comment by dallintine** [comment]
have it been done or yet to be done

**Comment by dave-ok** [comment]
@dallintine These are yet to be done. During our last meeting I was assigned these tasks. And hope to get them done ASAP, hence this issue. On explanations, I will try to explain as best as I can in the corresponding PR but for further explanation checkout the following links or  better yet a quick search will get you the info you need.
 
Facebook - https://developers.facebook.com/docs/apps/
Travis CI - https://docs.travis-ci.com/user/tutorial/
